## conda env export > environment.yml
# conda create -n python36 python=3.6
# conda create -n tensorflow python=3.6

name: data_analysis_mining
channels:
  - defaults
dependencies:
  - python=3.6   # or 2.7
  - numpy
  - matplotlib
  - pandas
  - keras
  - pymysql
  - xlrd
